name: Publish
on:
  push:
    branches:
      - master
jobs:
  build:
    if: "!(contains(github.event.head_commit.message, 'release'))"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        npm config set //registry.npmjs.org/:_authToken $TOKEN 
        npm install
        npm run build
        npm publish
      env:
        TOKEN: ${{secrets.NPM_TOKEN}}